# Generated by Django 5.2 on 2025-04-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True,
                help_text="Напишите свой id телеграмм",
                max_length=100,
                null=True,
                verbose_name="tg id",
            ),
        ),
    ]
