# Generated by Django 5.2 on 2025-04-19 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=10, verbose_name="day week")),
            ],
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spot",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку",
                        max_length=250,
                        verbose_name="spot",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Время, в которое необходимо выполнять привычку",
                        null=True,
                        verbose_name="time",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Действие, которое предоставляет собой привычка",
                        max_length=250,
                        verbose_name="action",
                    ),
                ),
                (
                    "sign_pleasant_habit",
                    models.BooleanField(
                        help_text="Привычка, которую можно привязать к выполнению полезной привычки",
                        verbose_name="sign_pleasant_habit",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[
                            ("m x-y * * *", "every hour"),
                            ("m x-y/2 * * *", "every 2 hours"),
                            ("m x-y/3 * * *", "every 3 hours"),
                            ("m x,z,y * * *", "3 times per day"),
                            ("m x,y * * *", "2 times per day"),
                            ("m h * * *", "every day"),
                            ("m h */2 * *", "every 2 days"),
                            ("m h */3 * *", "every 3 days"),
                            ("m h * * d", "selected days"),
                        ],
                        default="m h * * *",
                        help_text="Периодичность выполнения привычки для напоминания в днях.",
                        null=True,
                        verbose_name="periodicity",
                    ),
                ),
                (
                    "award",
                    models.CharField(
                        blank=True,
                        help_text="Чем пользователь должен себя вознаградить после выполнения.",
                        max_length=250,
                        null=True,
                        verbose_name="award",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        help_text="Время, которое предположительно потратит пользователь на выполнение привычки.",
                        verbose_name="time to complete",
                    ),
                ),
                (
                    "sign_publicity",
                    models.BooleanField(
                        help_text="Привычки можно публиковать в общий доступ, чтобы другие пользователи могли брать в пример чужие привычки.",
                        verbose_name="sign publicity",
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Время к которому пользователь закончит действие привычки",
                        null=True,
                        verbose_name="end time",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Привычка, которая связана с другой привычкой, важно указывать для полезных привычек, но не для приятных.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="related habit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
