# Generated by Django 5.2 on 2025-04-19 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="days_week",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите день, в который осуществляется привычка",
                null=True,
                to="habits.week",
                verbose_name="days_week",
            ),
        ),
    ]
